const { readToken } = require('../Config/encription');
const { salesReportControllers } = require('../Controllers');
const router = require('express').Router();

router.get('/getSalesByInvoice', readToken, salesReportControllers.getSalesByInvoice);
router.get('/getSalesByInvoiceTotalASC', readToken, salesReportControllers.getSalesByInvoiceTotalASC);
router.get('/getSalesByInvoiceTotalDSC', readToken, salesReportControllers.getSalesByInvoiceTotalDSC);
router.get('/getSalesByInvoiceTanggalASC', readToken, salesReportControllers.getSalesByInvoiceTanggalASC);
router.get('/getSalesByInvoiceTanggalDSC', readToken, salesReportControllers.getSalesByInvoiceTanggalDSC);
router.get('/getProfitHariIni', readToken, salesReportControllers.getProfitHariIni);
router.get('/getPenjualanHariIni', readToken, salesReportControllers.getPenjualanHariIni);
router.get('/getMenungguPembayaran', readToken, salesReportControllers.getMenungguPembayaran);
router.get('/getKonfirmasiPembayaran', readToken, salesReportControllers.getKonfirmasiPembayaran);
router.get('/getSedangProses', readToken, salesReportControllers.getSedangProses);
router.get('/getSedangDikirim', readToken, salesReportControllers.getSedangDikirim);
router.get('/getPesananTerkonfirmasi', readToken, salesReportControllers.getPesananTerkonfirmasi);
router.get('/getPesananDibatalkan', readToken, salesReportControllers.getPesananDibatalkan);
router.get('/getStockAkanHabis', readToken, salesReportControllers.getStockAkanHabis);
router.get('/getProfitMingguan', readToken, salesReportControllers.getProfitMingguan);
router.get('/getPenjualanObatMingguan', readToken, salesReportControllers.getPenjualanObatMingguan);
router.get('/getProfitBulanan', readToken, salesReportControllers.getProfitBulanan);
router.get('/getPenjualanObatBulanan', readToken, salesReportControllers.getPenjualanObatBulanan);
router.get('/getLaporanProduk', readToken, salesReportControllers.getLaporanProduk);
router.get('/getLaporanProdukTotalASC', readToken, salesReportControllers.getLaporanProdukTotalASC);
router.get('/getLaporanProdukTotalDSC', readToken, salesReportControllers.getLaporanProdukTotalDSC);
router.get('/getLaporanUser', readToken, salesReportControllers.getLaporanUser);
router.get('/getLaporanUserTotalASC', readToken, salesReportControllers.getLaporanUserTotalASC);
router.get('/getLaporanUserTotalDSC', readToken, salesReportControllers.getLaporanUserTotalDSC);
router.post('/getSearchInvoice', readToken, salesReportControllers.getSearchInvoice);
router.post('/getFilterInvoice', readToken, salesReportControllers.getFilterInvoice);
router.post('/getSearchProduct', readToken, salesReportControllers.getSearchProduct);
router.post('/getSearchUser', readToken, salesReportControllers.getSearchUser);

module.exports = router;